// src/app/components/multi-step-post-form/multi-step-post-form.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { PostService } from '../../services/post.service';
import { Post } from '../../models/post.model';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatStep, MatStepper, MatStepperModule } from '@angular/material/stepper';
import { MatCard, MatCardContent, MatCardTitle } from '@angular/material/card';
import { Step1Component } from "../multi-step-post-form/step1/step1.component";
import { Step2Component } from "../multi-step-post-form/step2/step2.component";

@Component({
  selector: 'app-multi-step-post-form',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    MatButtonModule,
    MatStepperModule,
    MatCard,
    MatCardTitle,
    MatCardContent,
    MatStep,
    MatStepper,
    Step1Component, // Explicitly listed for standalone imports
    Step2Component  // Explicitly listed for standalone imports
  ],
  templateUrl: './multi-step-form.component.html',
  styleUrls: ['./multi-step-form.component.css']
})

export class MultiStepPostFormComponent implements OnInit {
  private fb = inject(FormBuilder);
  private postService = inject(PostService);
  private router = inject(Router);

  masterForm: FormGroup = this.fb.group({
    step1: this.fb.group({
      title: ['', [Validators.required, Validators.minLength(3)]],
      slug: ['', [Validators.required, Validators.pattern(/^[a-z0-9-]+$/)]]
    }),
    step2: this.fb.group({
      excerpt: ['', Validators.required],
      description: ['', Validators.required],
      is_published: [false]
    })
  });

  activeStepIndex = 0;
  isLinear = true; // Enable linear stepper (must complete each step before moving forward)

  ngOnInit(): void {
    console.log('Step1 Form:', this.step1Form);
    console.log('Step2 Form:', this.step2Form);
  }

  get step1Form(): FormGroup {
    return this.masterForm.get('step1') as FormGroup;
  }

  get step2Form(): FormGroup {
    return this.masterForm.get('step2') as FormGroup;
  }

  nextStep(): void {
    if (this.activeStepIndex < 1 && this.masterForm.controls[this.getStepName()].valid) {
      this.activeStepIndex++;
    }
  }

  previousStep(): void {
    if (this.activeStepIndex > 0) {
      this.activeStepIndex--;
    }
  }

  onSubmit(): void {
    if (this.masterForm.valid) {
      const post: Post = {
        id: 0, // Will be generated by PostService or backend
        title: this.step1Form.get('title')?.value,
        slug: this.step1Form.get('slug')?.value,
        excerpt: this.step2Form.get('excerpt')?.value,
        description: this.step2Form.get('description')?.value,
        is_published: this.step2Form.get('is_published')?.value,
        created_at: new Date(),
        updated_at: new Date()
      };

      this.postService.addPost(post).subscribe({
        next: () => {
          this.router.navigate(['/']).then(r => console.log('Navigation result:', r));
        },
        error: (err) => console.error('Error creating post:', err)
      });
    }
  }

  private getStepName(): string {
    return `step${this.activeStepIndex + 1}`;
  }
}